services:
  # -------------------- Database --------------------
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playground
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app
  # -------------------- Gateway --------------------
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: gateway
    image: playground-nodejs-gateway:latest
    container_name: gateway
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
      APP: product
      PORT: 3000
      JAEGER_HTTP_COLLECTOR: jaeger:4318/api/traces
      MICROSERVICE_USER: http://nginx/user
      MICROSERVICE_PRODUCT: http://nginx/product
      JWT_SECRET: s9f8G7h6J5k4L3m2N1p0QwErTyUiOpAsDfGhJkLzXcVbNmQwErTyUiOpAsDfGh
    depends_on:
      - mysql-db
    networks:
      - app
  # -------------------- User Services --------------------
  user-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: user
    image: playground-nodejs-user:latest
    container_name: user-1
    environment:
      NODE_ENV: production
      APP: user-1
      SERVER_PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: userService
      DB_PASSWORD: password
      DB_DATABASE: nodeJsPlayground
      JWT_SECRET: s9f8G7h6J5k4L3m2N1p0QwErTyUiOpAsDfGhJkLzXcVbNmQwErTyUiOpAsDfGh
      JAEGER_HTTP_COLLECTOR: jaeger:4318/api/traces
    depends_on:
      - mysql-db
    networks:
      - app
  user-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: user
    image: playground-nodejs-user:latest
    container_name: user-2
    environment:
      NODE_ENV: production
      APP: user-2
      SERVER_PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: userService
      DB_PASSWORD: password
      DB_DATABASE: nodeJsPlayground
      JWT_SECRET: s9f8G7h6J5k4L3m2N1p0QwErTyUiOpAsDfGhJkLzXcVbNmQwErTyUiOpAsDfGh
      JAEGER_HTTP_COLLECTOR: jaeger:4318/api/traces
    depends_on:
      - mysql-db
    networks:
      - app
  # -------------------- Product Services --------------------
  product-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: product
    image: playground-nodejs-product:latest
    container_name: product-1
    environment:
      NODE_ENV: production
      APP: product-1
      SERVER_PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: userService
      DB_PASSWORD: password
      DB_DATABASE: nodeJsPlayground
      JAEGER_HTTP_COLLECTOR: jaeger:4318/api/traces
    depends_on:
      - mysql-db
    networks:
      - app
  product-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: product
    image: playground-nodejs-product:latest
    container_name: product-2
    environment:
      NODE_ENV: production
      APP: product-2
      SERVER_PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: userService
      DB_PASSWORD: password
      DB_DATABASE: nodeJsPlayground
      JAEGER_HTTP_COLLECTOR: jaeger:4318/api/traces
    depends_on:
      - mysql-db
    networks:
      - app
  # -------------------- Nginx --------------------
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway
      - user-1
      - user-2
      - product-1
      - product-2
    networks:
      - app
  # -------------------- Observability Stack --------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker-volumes/prometheus/dev/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "grafana-metricsdrilldown-app"
    depends_on:
      - prometheus
    volumes:
      - ./docker-volumes/grafana/provisioning:/etc/grafana/provisioning
      - ./docker-volumes/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - app
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app
  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-volumes/prometheus/dev/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP/gRPC
      - "4318:4318"     # OTLP/HTTP
      - "14268:14268"   # Collector HTTP endpoint
      - "6831:6831/udp" # Agent UDP
      - "6832:6832/udp"
    networks:
      - app
volumes:
  mysql_data:
networks:
  app:

